version: 2.1
orbs:
  node: circleci/node@1.1.6
  logzio-orb: logzio/logzio-orb@1.0.1
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: mkdir -p ~/reports
            - run: npm install
            - run:
                name: Run linter
                command: npm run lint:ci
            - run:
                name: Run unit tests with JUnit as reporter
                command: jest --ci --runInBand --reporters=default --reporters=jest-junit --coverage
                environment:
                  JEST_JUNIT_OUTPUT_DIR: "reports/junit/js-test-results.xml"
            - store_artifacts:
                path:  ~/project/coverage/lcov-report
                destination: coverage
      - logzio-orb/submit:
          dir-path: logs
workflows:
    build-and-test:
      jobs:
        - build-and-test