version: 2.1
orbs:
  node: circleci/node@1.1.6
  logzio-orb: logzio/logzio-orb@1.0.1
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - store_artifacts:
                path:  ~/project/coverage/lcov-report
                destination: coverage
      - logzio-orb/submit:
          dir-path: logs
workflows:
    build-and-test:
      jobs:
        - build-and-test